#### Importing python libraries

In [1]:
import tweepy
import simplejson as json

In [2]:
from tweepy import OAuthHandler

#### Entering account keys

In [3]:
consumer_key = '#####'
consumer_secret = '####'
access_token = '####'
access_secret = '####'

auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
 
api = tweepy.API(auth)

In [4]:
'''tweets = api.user_timeline(screen_name="midasIIITD").items() 
for tw in tweets:
    print(tw.text)'''

'tweets = api.user_timeline(screen_name="midasIIITD").items() \nfor tw in tweets:\n    print(tw.text)'

#### Parsing the data from midasIIITD handle

In [5]:
dlist = []

for status in tweepy.Cursor(api.user_timeline, screen_name='@midasIIITD', tweet_mode="extended").items():
    #print(status.full_text)
    dlist.append(status._json)

In [6]:
#print(dlist[1])

In [7]:
print(len(dlist))

344

In [8]:
print(type(dlist))
print(type(dlist[0]))

<class 'list'>
<class 'dict'>

#### Creating and storing the data in json file

In [9]:
with open('deep2.json', 'w') as file:   
    #, encoding='utf8'
    json.dump(dlist, file, indent = 4)

#json.dump(status._json, file, ...)

#### Reading the data from json file and displaying in tabular format

In [10]:
import pandas as pd

In [11]:
dlist2 = []
with open('deep2.json') as pp:
    dlist2 = json.load(pp)

In [12]:
print(dlist2[0])

{'full_text': 'Clarification: Our earlier post which indicates that the interview has been done is referring to the interviews of the candidates who have submitted applications and tasks in the first round (not through IIITD internship portal). The second round candidates yet to be interviewed.', 'favorite_count': 0, 'is_quote_status': False, 'contributors': None, 'geo': None, 'display_text_range': [0, 280], 'in_reply_to_user_id': None, 'id': 1115902611599822852, 'in_reply_to_user_id_str': None, 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None, 'user': {'friends_count': 43, 'description': 'MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.', 'notifications': False, 'is_translation_enabled': False, 'location': 'New Delhi, India', 'profile_background_image_url': None, 'profile_use_background_image': True, 'profile_background_color': 'F5F8FA', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'id': 1021355762575073281, 'utc_offset': None, 'screen_name': 'midasIIITD', 'followers_count': 290, 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1021355762575073281/1554320878', 'profile_text_color': '333333', 'verified': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_link_color': '1DA1F2', 'name': 'MIDAS IIITD', 'follow_request_sent': False, 'time_zone': None, 'is_translator': False, 'contributors_enabled': False, 'protected': False, 'listed_count': 0, 'entities': {'description': {'urls': []}, 'url': {'urls': [{'display_url': 'midas.iiitd.edu.in', 'indices': [0, 23], 'url': 'https://t.co/Uwg7oSM6mE', 'expanded_url': 'http://midas.iiitd.edu.in/'}]}}, 'lang': 'en', 'created_at': 'Mon Jul 23 11:26:04 +0000 2018', 'has_extended_profile': False, 'profile_background_image_url_https': None, 'favourites_count': 143, 'following': False, 'default_profile': True, 'profile_background_tile': False, 'geo_enabled': False, 'default_profile_image': False, 'profile_sidebar_border_color': 'C0DEED', 'statuses_count': 344, 'profile_sidebar_fill_color': 'DDEEF6', 'url': 'https://t.co/Uwg7oSM6mE', 'translator_type': 'none', 'id_str': '1021355762575073281'}, 'in_reply_to_screen_name': None, 'lang': 'en', 'retweet_count': 0, 'truncated': False, 'retweeted': False, 'id_str': '1115902611599822852', 'in_reply_to_status_id_str': None, 'favorited': False, 'place': None, 'entities': {'urls': [], 'symbols': [], 'user_mentions': [], 'hashtags': []}, 'coordinates': None, 'created_at': 'Wed Apr 10 09:01:29 +0000 2019'}

In [13]:
print(dlist[100]['full_text'])
print(dlist[100]['created_at'])
print(dlist[0]['favorite_count'])
print(dlist[90]['retweet_count'])
print(len(dlist))
cnt = 0
if ('media') in dlist[40]['entities']:
    #print("hello")
    if ('media') in dlist[40]['entities']:
        #print("hello2")
        temp = dlist[40]['entities']
        
        if ('media') in temp:
            #print("hello3")
            for i in temp['media']:
                if ('type') in i:
                    if i['type']=='photo':
                        cnt+=1
print(cnt)

#created_at
#favorite_count
#retweet_count
#
#print(dlist[0]['media'])

RT @MSFTResearch: Congratulations to Manik Varma, @iitdelhi's Himanshu Jain, Venkatesh Balasubramanian and Bhanu Chunduri for winning the Bâ€¦
Fri Feb 15 08:22:23 +0000 2019
0
2
344
0

In [15]:
import pandas as pd
df1 = pd.DataFrame(columns = ["text", "date_time", "likes", "retweets", "pics"])
df1

Empty DataFrame
Columns: [text, date_time, likes, retweets, pics]
Index: []

In [23]:
data = []
for i in range(len(dlist)):
    t1 = dlist[i]['full_text']
    t2 = dlist[i]['created_at']
    t3 = dlist[i]['favorite_count']
    t4 = dlist[i]['retweet_count']
    cnt = 0
    if ('media') in dlist[40]['entities']:
        #print("hello")
        if ('media') in dlist[40]['entities']:
            #print("hello2")
            temp = dlist[40]['entities']
        
            if ('media') in temp:
                #print("hello3")
                for i in temp['media']:
                    if ('type') in i:
                        if i['type']=='photo':
                            cnt+=1
    t5 = cnt
    if cnt==0:
        t5 = "None"
    
    temp = {"text":t1, "date_time":t2, "likes":t3, "retweets":t4, "pics":t5}
    data.append(temp)
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343

In [25]:
df1 = pd.DataFrame(data)
df1 = df1[["text", "date_time", "likes", "retweets", "pics"]]
df1

,text,date_time,likes,retweets,pics
0,Clarification: Our earlier post which indicate...,Wed Apr 10 09:01:29 +0000 2019,0,0,None
1,RT @IIITDelhi: Applications open for MTech (CB...,Wed Apr 10 04:51:26 +0000 2019,0,1,None
2,RT @IIITDelhi: We are delighted to share that ...,Tue Apr 09 16:45:07 +0000 2019,0,14,None
3,RT @Harvard: Professor Jelani Nelson founded A...,Tue Apr 09 05:04:27 +0000 2019,0,35,None
4,RT @emnlp2019: For anyone interested in submit...,Tue Apr 09 05:04:11 +0000 2019,0,17,None
5,RT @multimediaeval: Announcing the 2019 MediaE...,Mon Apr 08 19:38:09 +0000 2019,0,15,None
6,"Many Congratulations to @midasIIITD student, S...",Mon Apr 08 07:08:12 +0000 2019,18,2,None
7,@midasIIITD thanks all students who have appea...,Mon Apr 08 03:27:42 +0000 2019,5,0,None
8,"@himanchalchandr Meanwhile, complete CV/NLP ta...",Sun Apr 07 14:17:29 +0000 2019,0,0,None
9,@sayangdipto123 Submit as per the guideline ag...,Sun Apr 07 14:17:09 +0000 2019,0,0,None
10,We request all students whose interview are sc...,Sun Apr 07 11:43:24 +0000 2019,1,1,None
11,"Other queries: ""none of the Tweeter Apis give ...",Sun Apr 07 06:55:19 +0000 2019,5,2,None
12,"Other queries: ""do we have to make two differe...",Sun Apr 07 06:53:38 +0000 2019,4,1,None
13,"Other queries: ""If using Twitter api, it does ...",Sun Apr 07 05:32:27 +0000 2019,6,1,None
14,Response to some queries asked by students on ...,Sun Apr 07 05:29:40 +0000 2019,7,1,None
15,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,Sat Apr 06 17:11:29 +0000 2019,0,2,None
16,@nupur_baghel @PennDATS Congratulation @nupur_...,Sat Apr 06 16:43:27 +0000 2019,18,3,None
17,We have emailed the task details to all candid...,Fri Apr 05 16:08:37 +0000 2019,11,1,None
18,RT @rfpvjr: Our NAACL paper on polarization in...,Fri Apr 05 04:05:11 +0000 2019,0,16,None
19,RT @kdnuggets: Effective Transfer Learning For...,Fri Apr 05 04:04:43 +0000 2019,0,11,None
20,RT @stanfordnlp: Whatâ€™s new in @Stanford CS224...,Wed Apr 03 18:31:53 +0000 2019,0,59,None
21,RT @DeepMindAI: Today we're releasing a large-...,Wed Apr 03 17:04:32 +0000 2019,0,872,None
22,RT @ylecun: Congratulations Jitendra Malik !\n...,Wed Apr 03 09:03:40 +0000 2019,0,16,None
23,RT @IIITDelhi: Another chance to take admissio...,Wed Apr 03 07:46:02 +0000 2019,0,4,None
24,Dear @midasIIITD internship candidates who hav...,Tue Apr 02 04:20:13 +0000 2019,8,1,None
25,Looking forward to your paper submission to @I...,Tue Apr 02 02:44:54 +0000 2019,5,1,None
26,RT @ngrams: Reproducibility in multimedia rese...,Tue Apr 02 02:35:44 +0000 2019,0,7,None
27,Online application for https://t.co/DJFDrQsHZP...,Mon Apr 01 06:53:08 +0000 2019,7,2,None
28,RT @ACMMM19: A final reminder of the Reproduci...,Sun Mar 31 10:21:24 +0000 2019,0,10,None
29,RT @isarth23: Thanks for the support and help ...,Fri Mar 29 19:43:24 +0000 2019,0,2,None
...,...,...,...,...,...
314,RT @TensorFlow: TensorFlow 1.10.0 has been rel...,Thu Aug 09 05:59:57 +0000 2018,0,265,None
315,@midasIIITD is looking for motivated IIITD MTe...,Wed Aug 08 11:30:56 +0000 2018,2,1,None
316,@IIITDelhi @ponguru @RatnRajiv The results of ...,Wed Aug 08 05:53:48 +0000 2018,3,1,None
317,RT @IIITDelhi: @midasIIITD has secured rank 1 ...,Wed Aug 08 05:45:58 +0000 2018,0,1,None
318,RT @kdnuggets: Comparison of Top 6 Python NLP ...,Tue Aug 07 07:16:33 +0000 2018,0,40,None
319,Check more details of the 20th IEEE Internatio...,Tue Aug 07 02:05:12 +0000 2018,1,1,None
320,MR2AMC@ISM 2018 will be organized by @RatnRaji...,Tue Aug 07 01:58:49 +0000 2018,1,1,None
321,"Our workshop proposal named, ""MR2AMC: Multimod...",Tue Aug 07 01:50:33 +0000 2018,1,1,None
322,@NUSComputing Congratulations Abdelhak and Pro...,Mon Aug 06 17:48:23 +0000 2018,0,0,None
323,RT @goodfellow_ian: One of the most anticipate...,Mon Aug 06 17:46:59 +0000 2018,0,103,None
324,@the_dhumketu Great to have you in @midasIIITD,Mon Aug 06 06:06:47 +0000 2018,0,0,None
325,Congratulation @soujanyaporia for being appoin...,Fri Aug 03 05:56:33 +0000 2018,6,1,None
326,@IIITDelhi @the_dhumketu Thanks team @midasIII...,Wed Aug 01 11:47:15 +0000 2018,5,1,None
327,RT @IIITDelhi: Congratulations @midasIIITD int...,Wed Aug 01 11:20:07 +0000 2018,0,4,None
328,RT @learning_pt: Profile of the 5 Indian under...,Wed Aug 01 05:06:47 +0000 2018,0,4,None
329,Have a look at the list of accepted papers in ...,Tue Jul 31 12:11:52 +0000 2018,1,0,None
330,RT @goodfellow_ian: https://t.co/hYiWI7ntyk Te...,Tue Jul 31 02:06:26 +0000 2018,0,264,None
331,RT @IIITDelhi: Congratulations Dr. @RatnRajiv ...,Mon Jul 30 07:30:51 +0000 2018,0,2,None
332,"RT @ylecun: Jitendra Malik, who directs FAIR-M...",Sat Jul 28 11:07:11 +0000 2018,0,57,None
333,RT @kdnuggets: .@Bloomberg launches free cours...,Sat Jul 28 06:14:09 +0000 2018,0,105,None
334,RT @TechAtBloomberg: Missed #PyLondinium18? Wa...,Sat Jul 28 06:13:48 +0000 2018,0,7,None
335,RT @IIITDelhi: We are delighted to announce th...,Sat Jul 28 04:08:21 +0000 2018,0,6,None
336,Get ready for the annual technical fest of @II...,Fri Jul 27 06:46:44 +0000 2018,3,2,None
337,Congratulations Dr. @RatnRajiv and team @midas...,Fri Jul 27 04:07:31 +0000 2018,8,2,None
338,Congratulations MIDAS @midasIIITD intern Prakh...,Wed Jul 25 05:14:35 +0000 2018,5,1,None
339,MIDAS@IIITD foundation. https://t.co/LKuzyBHzjm,Tue Jul 24 10:33:23 +0000 2018,2,1,None
340,It feels great to be the part of @IIITDelhi. h...,Tue Jul 24 10:12:34 +0000 2018,2,1,None
341,"Thank you, @toonzratn for designing the logo o...",Tue Jul 24 09:46:26 +0000 2018,4,1,None
342,We are on Facebook too. Like our page to get o...,Mon Jul 23 16:25:05 +0000 2018,3,1,None
343,MIDAS is a group of researchers at IIIT-Delhi ...,Mon Jul 23 12:53:15 +0000 2018,7,4,None